# Shadowrocket: 2026-07-03 19:47:38
[General]
include = Phone.conf
update-url = https://raw.githubusercontent.com/ssstshx/Sin/refs/heads/main/Shadowrocket/porxy_list.conf

[Proxy Group]
直连list = select,DIRECT
porxylist = select,PROXY,香港节点,台湾节点,日本节点,新加坡节点,韩国节点,美国节点,policy-select-name=PROXY,interval=86400,timeout=5,select=0,url=http://www.gstatic.com/generate_204

[Rule]
DOMAIN-SUFFIX,jsdelivr.net,DIRECT
RULE-SET,https://raw.githubusercontent.com/ssstshx/Sin/refs/heads/main/ProxyLite.list,PROXY
